# Generated by Django 3.1.1 on 2020-11-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='about',
        ),
    ]
